### ISSUE TITLE
Pyglow - Meteor Shower 

### ISSUE THREAD

**Issue by dave7802** [Breakfast-for-Pigeons/PiGlow#1]
Did you ever get this working? 
If not have you looked at something called IFFT 
You could use this to look for the Meteor shower, and when active triggers your script on the PI.

Just a point in a direction, sorry to raise as a issue, no other way to contact.
Was just browsing to see how adventus people are with the Pyglow

Cheers

**Comment by Breakfast-for-Pigeons** [comment]
Never did get it to work. This is so far on the back burner, I don't think I'll ever get around to it.  Thanks for the info on IFFT.
