### ISSUE TITLE
Raspberry Pi Model B w/Piglow

### ISSUE THREAD

**Issue by pbouthil** [Breakfast-for-Pigeons/PiGlow#4]
I am unable to get any of your Python Piglow programs to work. I have a old RPi Model B with Piglow LED card installed. I followed the install instructions from benlab with no luck. I am able to setup and run all  Boeeerb Python Piglow examples with no issues using his install procedure. I am running Raspbian Stretch OS. Please help.

**Comment by Breakfast-for-Pigeons** [comment]
Hi pbouthil,
Thank you so much for writing! I'd be happy to help you out. And the first way to do that is to upload the changes I made to my programs.  Once I get them uploaded (hopefully in the next day or so), I will let you know. I will also update the instructions on my Piglow page.  Again, thanks for bringing this to my attention. I wanted people to enjoy my programs.
Paul

**Comment by Breakfast-for-Pigeons** [comment]
Hi pbouthil,
The programs should be working now. I uploaded the code. Then got out my Raspberry Pi model B and they ran just fine.  Just type **sudo python3** _program-name_.py   Thanks again for bringing this to my attention.  Let me know if the programs work for you.

**Comment by pbouthil** [comment]
Thank you for the update. I will let you know if all is working.

**Comment by pbouthil** [comment]
I just checked out all your python scripts and they all work. Thanks again for updating them.

**Comment by Breakfast-for-Pigeons** [comment]
Glad to hear they are working for you.  These were some of my first python programs. As I was uploading the correct programs, I noticed how sloppy my coding was. The programs still work as intended, but I saw plenty of ways that I can optimize my code and make the programs more customizable.  This will be one of my next projects.
